apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-hw
  labels:
    app: prometheus-hw
  namespace: monitoring
spec:
  jobLabel: prometheus-hw
  selector:
    matchLabels:
      app: prometheus-hw
  endpoints:
  - interval: 30s
    port: web
    path: /actuator/prometheus